In [32]:
# импорт библиотек
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
# считываем и кодируем данные
data = pd.read_csv('mushrooms.csv')
data['class'] = data['class'].apply(lambda x: ['p', 'e'].index(x))

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0         0         x           s         n       t    p               f   
1         1         x           s         y       t    a               f   
2         1         b           s         w       t    l               f   
3         0         x           y         w       t    p               f   
4         1         x           s         g       f    n               f   
...     ...       ...         ...       ...     ...  ...             ...   
8119      1         k           s         n       f    n               a   
8120      1         x           s         n       f    n               a   
8121      1         f           s         n       f    n               a   
8122      0         k           y         n       f    y               f   
8123      1         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [17]:
enc = OneHotEncoder()
enc.fit(data[data.columns[1:23]])

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

data['class'] = data['class'].astype(str).astype(float)
data.dtypes

In [18]:
data2 = enc.transform(data[data.columns[1:23]]).toarray()
data2 # получили нампаевский массив

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
# делим данные на тренировочные и тестовые (обучать будем на всех данных)
X = data.loc[:, 'cap-shape':].values
y = data['class'].values
X_train, X_test, y_train, y_test = train_test_split(data2, y) 
print(X_train)
print(y_train)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[1 1 0 ... 1 1 0]


In [23]:
# объявляем модель
gnb = GaussianNB()
gnb.fit(X_train, y_train)
preds = gnb.predict(X_test)

[0 0 1 ... 1 0 1]


In [30]:
metrics.accuracy_score(y_test, preds)

0.966518956179222

In [33]:
# Какие наиболее распространенные признаки несъедобных грибов?
pd.crosstab(data['cap-shape'], data['class']) # среди несъедобных грибов много представителей с плоской (f) и впалой (x) шляпкой

class         0     1
cap-shape            
b            48   404
c             4     0
f          1556  1596
k           600   228
s             0    32
x          1708  1948

In [37]:
pd.crosstab(data['cap-surface'], data['class']) # больше всего несъедобных грибов с волокнистой (f) и чешуйчатой (y) шляпкой

class           0     1
cap-surface            
f             760  1560
g               4     0
s            1412  1144
y            1740  1504

In [36]:
pd.crosstab(data['cap-color'], data['class']) # преобладают несъедобные грибы с серой (g) и коричневой (n) шляпкой

class         0     1
cap-color            
b           120    48
c            12    32
e           876   624
g           808  1032
n          1020  1264
p            88    56
r             0    16
u             0    16
w           320   720
y           672   400

In [38]:
pd.crosstab(data['bruises'], data['class']) # подаавляющее большинство несъедобных грибов имеет вмятины (t)

class       0     1
bruises            
f        3292  1456
t         624  2752

In [44]:
pd.crosstab(data['stalk-shape'], data['class']) # у многих несъедобных грибов ножка коническая (t)

class           0     1
stalk-shape            
e            1900  1616
t            2016  2592

In [41]:
pd.crosstab(data['veil-color'], data['class']) # у большинства несъедобных грибов покрывало белого цвета (w)

class          0     1
veil-color            
n              0    96
o              0    96
w           3908  4016
y              8     0

In [42]:
pd.crosstab(data['ring-number'], data['class']) # у большинства несъедобных грибов 1 кольцо (о)

class           0     1
ring-number            
n              36     0
o            3808  3680
t              72   528

In [45]:
# Где чаще всего растут несъедобные грибы?
pd.crosstab(data['habitat'], data['class']) # большая часть несъедобных грибов растет в лесах (d) и траве (g)

class       0     1
habitat            
d        1268  1880
g         740  1408
l         592   240
m          36   256
p        1008   136
u         272    96
w           0   192